project_id = "usmwwkltvjyjzaxsdyhz"

[functions.send-application]
verify_jwt = false

[functions.send-application-notification]
verify_jwt = false

[functions.send-resume]
verify_jwt = false

[functions.increment-view]
verify_jwt = false

[functions.webhook-dispatcher]
verify_jwt = false