-- Делаем employer_id nullable для демо-вакансий
ALTER TABLE vacancies ALTER COLUMN employer_id DROP NOT NULL;

-- Добавляем флаг для демо-вакансий
ALTER TABLE vacancies ADD COLUMN IF NOT EXISTS is_demo boolean DEFAULT false;

-- Вставляем демо-вакансии без employer_id
INSERT INTO vacancies (title, location, employment_type, salary_min, salary_max, description, is_demo, employer_id) VALUES
-- Buenos Aires (CABA) - 10 вакансий
('Cajero/a de Supermercado', 'Buenos Aires, CABA', 'Tiempo completo', 180000, 220000, 'Importante cadena de supermercados busca cajeros/as para turno mañana y tarde. Requisitos: secundario completo, experiencia en atención al cliente (excluyente), manejo de PC básico. Ofrecemos: estabilidad laboral, obra social, descuentos en compras. Contacto: mdpargmvd@gmail.com', true, NULL),
('Mozo/a de Restaurante', 'Buenos Aires, CABA', 'Tiempo completo', 200000, 250000, 'Restaurante de alta cocina en Palermo busca mozos/as con experiencia. Se requiere: secundario completo, mínimo 1 año de experiencia en gastronomía, excelente presencia, buena dicción. Horario: turnos rotativos. Beneficios: propinas, comida, capacitación. Email: mdpargmvd@gmail.com', true, NULL),
('Operador/a de Call Center', 'Buenos Aires, CABA', 'Tiempo completo', 190000, 230000, 'Empresa líder en telecomunicaciones busca operadores telefónicos para atención al cliente. Requisitos: secundario completo, buena dicción, disponibilidad horaria. Ofrecemos: capacitación paga, trabajo en equipo, bonos por productividad. Zona: Microcentro. Contacto: mdpargmvd@gmail.com', true, NULL),
('Vendedor/a de Local Comercial', 'Buenos Aires, CABA', 'Tiempo completo', 210000, 280000, 'Reconocida marca de indumentaria busca vendedores/as para local en shopping. Se requiere: experiencia en ventas, buena presencia, proactividad, manejo de caja. Beneficios: comisiones atractivas, descuentos en productos, ambiente joven. Enviar CV a: mdpargmvd@gmail.com', true, NULL),
('Repartidor/a con Moto Propia', 'Buenos Aires, CABA', 'Tiempo completo', 250000, 350000, 'App de delivery busca repartidores con moto propia. Requisitos: moto 110cc o superior, registro de conducir vigente, smartphone. Beneficios: horarios flexibles, pagos semanales, bonos por entregas. Zonas: CABA y GBA. Contacto: mdpargmvd@gmail.com', true, NULL),
('Guardia de Seguridad', 'Buenos Aires, CABA', 'Tiempo completo', 220000, 260000, 'Empresa de seguridad privada busca guardias para edificios corporativos. Requisitos: secundario completo, curso de vigilador (excluyente), disponibilidad para turnos rotativos. Ofrecemos: estabilidad, capacitación continua, uniforme. Email: mdpargmvd@gmail.com', true, NULL),
('Administrativo/a de Oficina', 'Buenos Aires, CABA', 'Tiempo completo', 240000, 300000, 'Estudio contable busca administrativo/a para tareas generales de oficina. Requisitos: secundario completo, manejo de Excel intermedio, experiencia en facturación y archivo. Zona: Recoleta. Horario: lunes a viernes 9 a 18hs. Contacto: mdpargmvd@gmail.com', true, NULL),
('Cocinero/a de Restaurant', 'Buenos Aires, CABA', 'Tiempo completo', 280000, 350000, 'Restaurante italiano busca cocinero/a con experiencia en cocina tradicional. Requisitos: mínimo 2 años de experiencia, conocimiento de pastas frescas, trabajo en equipo. Horario: cenas. Beneficios: comida, propinas, buen ambiente laboral. Email: mdpargmvd@gmail.com', true, NULL),
('Limpieza y Mantenimiento', 'Buenos Aires, CABA', 'Medio tiempo', 150000, 180000, 'Empresa de limpieza busca personal para oficinas y edificios. Requisitos: experiencia comprobable, referencias laborales, disponibilidad horaria. Turnos: mañana o tarde. Zona: Puerto Madero. Enviar CV a: mdpargmvd@gmail.com', true, NULL),
('Repositor/a de Mercadería', 'Buenos Aires, CABA', 'Tiempo completo', 190000, 220000, 'Cadena de autoservicios necesita repositores para turno noche. Requisitos: secundario completo, disponibilidad horaria nocturna (22 a 6hs), experiencia en supermercados. Ofrecemos: estabilidad, adicional nocturno, obra social. Contacto: mdpargmvd@gmail.com', true, NULL),

-- Córdoba - 5 vacansias
('Vendedor/a de Local', 'Córdoba Capital', 'Tiempo completo', 180000, 240000, 'Importante cadena de electrodomésticos busca vendedores/as. Requisitos: secundario completo, experiencia en ventas, conocimientos básicos de productos tecnológicos. Beneficios: comisiones atractivas, capacitación. Zona: Centro. Email: mdpargmvd@gmail.com', true, NULL),
('Cajero/a Bancario', 'Córdoba Capital', 'Tiempo completo', 220000, 280000, 'Entidad financiera busca cajeros/as. Requisitos: secundario completo, experiencia en manejo de efectivo, atención al público, disponibilidad inmediata. Ofrecemos: estabilidad, capacitación, beneficios bancarios. Contacto: mdpargmvd@gmail.com', true, NULL),
('Chofer de Reparto', 'Córdoba Capital', 'Tiempo completo', 230000, 280000, 'Distribuidora de bebidas busca chofer con registro profesional. Requisitos: registro C1 vigente, experiencia en reparto, conocimiento de la ciudad. Ofrecemos: vehículo de la empresa, viáticos, estabilidad laboral. Email: mdpargmvd@gmail.com', true, NULL),
('Recepcionista de Hotel', 'Córdoba Capital', 'Tiempo completo', 200000, 250000, 'Hotel 4 estrellas busca recepcionista bilingüe (inglés intermedio). Requisitos: experiencia en hotelería, manejo de sistemas de reservas, excelente presencia, turnos rotativos. Zona: Nueva Córdoba. Contacto: mdpargmvd@gmail.com', true, NULL),
('Operario de Producción', 'Córdoba Capital', 'Tiempo completo', 210000, 260000, 'Fábrica de alimentos busca operarios para línea de producción. Requisitos: secundario completo, disponibilidad para turnos rotativos, experiencia en industria (deseable). Beneficios: comedor en planta, transporte. Email: mdpargmvd@gmail.com', true, NULL),

-- Rosario - 3 vacansias
('Mozo/a de Cafetería', 'Rosario, Santa Fe', 'Tiempo completo', 180000, 230000, 'Cafetería céntrica busca mozo/a con experiencia. Requisitos: mínimo 6 meses de experiencia, buena presencia, manejo de bandeja. Horario: lunes a sábado, turnos mañana y tarde. Propinas a parte. Contacto: mdpargmvd@gmail.com', true, NULL),
('Auxiliar de Farmacia', 'Rosario, Santa Fe', 'Tiempo completo', 200000, 250000, 'Farmacia de cadena busca auxiliar para atención y venta. Requisitos: secundario completo, experiencia en farmacia (deseable), buena predisposición. Zona: Centro. Turnos rotativos. Email: mdpargmvd@gmail.com', true, NULL),
('Personal de Limpieza', 'Rosario, Santa Fe', 'Medio tiempo', 140000, 170000, 'Empresa de limpieza busca personal para consorcios. Requisitos: experiencia, referencias laborales, responsabilidad. Zona: Pichincha. Horario: mañanas. Enviar CV a: mdpargmvd@gmail.com', true, NULL),

-- Mendoza - 3 vacansias  
('Vendedor/a de Vinoteca', 'Mendoza Capital', 'Tiempo completo', 190000, 250000, 'Vinoteca boutique busca vendedor/a con conocimientos de vinos. Requisitos: experiencia en ventas, conocimiento de vinos mendocinos, buena presencia, inglés básico. Zona: Centro. Comisiones por ventas. Contacto: mdpargmvd@gmail.com', true, NULL),
('Ayudante de Cocina', 'Mendoza Capital', 'Tiempo completo', 170000, 210000, 'Restaurante parrilla busca ayudante de cocina. Requisitos: experiencia en gastronomía, disponibilidad horaria, proactividad. Funciones: preparación de ingredientes, limpieza, apoyo al cocinero. Email: mdpargmvd@gmail.com', true, NULL),
('Empleado/a de Estación de Servicio', 'Mendoza Capital', 'Tiempo completo', 180000, 220000, 'Estación de servicio YPF busca playero/a. Requisitos: secundario completo, disponibilidad para turnos rotativos, buena predisposición. Funciones: carga de combustible, atención de shop, limpieza. Contacto: mdpargmvd@gmail.com', true, NULL),

-- La Plata - 2 vacacias
('Promotor/a de Ventas', 'La Plata, Buenos Aires', 'Tiempo completo', 200000, 270000, 'Empresa de telecomunicaciones busca promotores para stand en shopping. Requisitos: secundario completo, experiencia en ventas, buena presencia. Beneficios: fijo + comisiones, capacitación. Email: mdpargmvd@gmail.com', true, NULL),
('Cadete con Moto', 'La Plata, Buenos Aires', 'Tiempo completo', 180000, 240000, 'Estudio jurídico busca cadete con moto propia. Requisitos: moto, registro de conducir, conocimiento de la ciudad, celular. Funciones: trámites bancarios, gestiones administrativas. Contacto: mdpargmvd@gmail.com', true, NULL),

-- Mar del Plata - 2 vacacias
('Empleado/a de Parrilla', 'Mar del Plata, Buenos Aires', 'Tiempo completo', 190000, 250000, 'Parrilla céntrica busca parrillero/a con experiencia. Requisitos: mínimo 2 años de experiencia en parrilla, disponibilidad fines de semana, temporada de verano (excluyente). Propinas a parte. Email: mdpargmvd@gmail.com', true, NULL),
('Vendedor/a de Playa', 'Mar del Plata, Buenos Aires', 'Temporal', 150000, 200000, 'Concesionario de playa busca vendedores para temporada de verano. Requisitos: buena presencia, excelente trato con turistas, disponibilidad diciembre-marzo. Zona: playas céntricas. Contacto: mdpargmvd@gmail.com', true, NULL);